# Generated by Django 3.2.13 on 2022-05-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHACLPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('pattern_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pattern.classpattern')),
            ],
        ),
    ]
