# Generated by Django 3.2.13 on 2022-05-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0003_shaclpattern_shacl_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpattern',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shaclpattern',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
