# Generated by Django 3.2.13 on 2022-05-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterninstance',
            name='creator',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
